server:
    forward-headers-strategy: framework

springdoc:
  swagger-ui:

      oauth:
        client-secret: swagger
        app-name: swagger
        client-id: swagger
      persist-authorization: true
      display-request-duration: true
      doc-expansion: true
      enabled: true

spring:
    application:
        name: partibremen
    datasource:
        password: 123
        url: jdbc:mysql://localhost:3316/parti?useSSl=false/partibremen
        username: 123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true
